Controllers/CarTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisPark.Models;

namespace SisPark.Controllers
{
    [Authorize(Roles="Administrador")]
    public class CarTypesController : Controller
    {

        private SisparkModel db = new SisparkModel();

        //
        // GET: /CarTypes/

        public ActionResult Index()
        {
            return View(db.CarType.ToList());
        }

        //
        // GET: /CarTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CarTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarType cartype)
        {
            if (ModelState.IsValid)
            {
                db.CarType.Add(cartype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartype);
        }

        //
        // GET: /CarTypes/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CarType cartype = db.CarType.Find(id);
            if (cartype == null)
            {
                return HttpNotFound();
            }
            return View(cartype);
        }

        //
        // POST: /CarTypes/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarType cartype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartype);
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisPark.Models;

namespace SisPark.Controllers
{
    [Authorize(Roles = "Administrador,App User,Auditor")]
    public class CarsController : Controller
    {
        private SisparkModel db = new SisparkModel();

        //
        // GET: /Cars/

        public ActionResult Index()
        {
            var car = db.Car.Include(c => c.CarType);
            return View(car.ToList());
        }


        //
        // GET: /Cars/Create

        public ActionResult Create()
        {
            ViewBag.CarTypeId = new SelectList(db.CarType, "CarTypeId", "description");
            return View();
        }

        //
        // POST: /Cars/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                var caridentico = db.Car.FirstOrDefault(c => c.Patente == car.Patente);
                if (caridentico == null)
                {
                    db.Car.Add(car);
                    db.SaveChanges();
                    return RedirectToAction("TicketEntrada", "Tickets", new { carId = car.CarId });
                }
                else
                {
                    ModelState.AddModelError("", String.Concat("Ya hay un auto con la patente: ", caridentico.Patente));
                }
            }
            ViewBag.CarTypeId = new SelectList(db.CarType, "CarTypeId", "description", car.CarTypeId);
            return View(car);
        }

        //
        // GET: /Cars/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Car car = db.Car.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarTypeId = new SelectList(db.CarType, "CarTypeId", "description", car.CarTypeId);
            return View(car);
        }

        //
        // POST: /Cars/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                    db.Entry(car).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }
            ViewBag.CarTypeId = new SelectList(db.CarType, "CarTypeId", "description", car.CarTypeId);
            return View(car);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/UserLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisPark.Models;
using System.Web.Security;

namespace SisPark.Controllers
{
    [Authorize]
    public class UserLogsController : Controller
    {


        private SisparkModel db = new SisparkModel();
        public static void GuardarLogInLog(User user)
        {
            using (var db = new SisparkModel())
            {
            var sysUserLog = db.UserLog.Create();
            sysUserLog.UserId = user.UserId;
            sysUserLog.FechaYHora = DateTime.Now;
            sysUserLog.Accion = "Login";

            db.UserLog.Add(sysUserLog);
            db.SaveChanges();
            }
        }



        public static void GuardarLogOutLog(string LoggedUser)
        {

            using (var db = new SisparkModel())
            {
                var user = db.User.FirstOrDefault(u => u.Usuario == LoggedUser);
                var sysUserLog = db.UserLog.Create();
                sysUserLog.UserId = user.UserId;
                sysUserLog.FechaYHora = DateTime.Now;
                sysUserLog.Accion = "Logout";
               
                db.UserLog.Add(sysUserLog);
                db.SaveChanges();
            }
        }
        // Buscar por        USUARIO=x 
        //                   Fecha> y fecha< 
        //                   accion=login o logout
        [Authorize(Roles = "Administrador,Auditor")]
        public ActionResult Index(string LogAccion, string userseek, string fechaDesde, string fechaHasta)
        {
            var ListaAccion = new List<string>();

            var ConsultaAccion = from d in db.UserLog
                              orderby d.Accion
                              select d.Accion;
            ListaAccion.AddRange(ConsultaAccion.Distinct());
            ViewBag.LogAccion = new SelectList(ListaAccion);

            var ListaUser = new List<string>();

            var ConsultaUser = from u in db.UserLog
                               orderby u.User.Usuario
                               select u.User.Usuario;
            ListaUser.AddRange(ConsultaUser.Distinct());
            ViewBag.userseek = new SelectList(ListaUser);

            var ulogs = from l in db.UserLog
                        select l;

            if (!String.IsNullOrEmpty(fechaDesde))
            {
                DateTime fecha1 = Convert.ToDateTime(fechaDesde);
                ulogs = ulogs.Where(fd => fd.FechaYHora >= fecha1);
            }
            if (!String.IsNullOrEmpty(fechaHasta))
            {
                DateTime fecha2 = Convert.ToDateTime(fechaHasta);
                ulogs = ulogs.Where(fd => fd.FechaYHora <= fecha2);
            }
            if (!String.IsNullOrEmpty(userseek))
            {
                ulogs = ulogs.Where(c => c.User.Usuario == userseek);
            }

            if (string.IsNullOrEmpty(LogAccion))
                return View(ulogs);
            else
            {
                return View(ulogs.Where(x => x.Accion == LogAccion));
            }
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/UserTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisPark.Models;
using System.Web.Security;

namespace SisPark.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UserTypesController : Controller
    {
        private SisparkModel db = new SisparkModel();
        //
        // GET: /UserTypes/
        public ActionResult Index()
        {
            return View(db.Usertype.ToList());
        }

        //
        // GET: /UserTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usertype usertype)
        {
            if (ModelState.IsValid)
            {
                var ut = db.Usertype.FirstOrDefault(u => u.description == usertype.description);
                if (ut == null)
                {
                    db.Usertype.Add(usertype);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Tipo de usuario Repetido");
                }
                
                
            }

            return View(usertype);
        }

        //
        // GET: /UserTypes/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Usertype usertype = db.Usertype.Find(id);
            if (usertype == null)
            {
                return HttpNotFound();
            }
            return View(usertype);
        }

        //
        // POST: /UserTypes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usertype usertype)
        {
            if (ModelState.IsValid)
            {
                // Comprueba que no haya un tipo de usuario igual
                var ut = db.Usertype.FirstOrDefault(u => u.description == usertype.description);
                if (ut == null)
                {
                    db.Entry(usertype).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Ya existe un tipo de usuario igual");
                }
            }
            return View(usertype);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - SISPARK</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Logo", "Index", new { controller = "Home" }, new { @class = "logo" })</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            @if (User.IsInRole("Administrador"))
                            {
                                <li>@Html.ActionLink("Ticket", "Index", "Tickets")</li>
                                <li>@Html.ActionLink("Auto", "Index", "Cars")</li>
                                <li>@Html.ActionLink("Tipo de Auto", "Index", "CarTypes")</li>
                                <li>@Html.ActionLink("Usuario", "Index", "Users")</li>
                                <li>@Html.ActionLink("Tipo de Usuario", "Index", "UserTypes")</li>
                                <li>@Html.ActionLink("Estado del Ticket", "Index", "TicketStates")</li>
                                <li>@Html.ActionLink("Log de Usuario", "Index", "UserLogs")</li>
                                <li>@Html.ActionLink("Log de Ticket", "Index", "TicketLogs")</li>
                                <li>@Html.ActionLink("Parametro", "Index", "Parameters")</li>
                            }

                            @if (User.IsInRole("App User"))
                            {
                                <li>@Html.ActionLink("Ticket", "Index", "Tickets")</li>
                                <li>@Html.ActionLink("Auto", "Index", "Cars")</li>
                            }
                            
                            @if (User.IsInRole("Auditor"))
                            {
                                <li>@Html.ActionLink("Log de Usuario", "Index", "UserLogs")</li>
                                <li>@Html.ActionLink("Log de Ticket", "Index", "TicketLogs")</li>
                                <li>@Html.ActionLink("Parametro", "Index", "Parameters")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - SISPARK</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        
        @RenderSection("scripts", required: false)
    </body>
</html>