Models/TicketLog.cs
namespace SisPark.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TicketLog")]
    public partial class TicketLog
    {
        public int TicketLogId { get; set; }

        public int TicketId { get; set; }

        public int UserId { get; set; }

        [Required]
        [StringLength(50)]
        public string TransactionType { get; set; }

        public DateTime DateTimeLog { get; set; }

        public virtual Ticket Ticket { get; set; }

        public virtual User User { get; set; }
    }
}

Controllers/TicketLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisPark.Models;
using System.Web.Security;

namespace SisPark.Controllers
{
    [Authorize]
    public class TicketLogsController : Controller
    {


        private SisparkModel db = new SisparkModel();
        [Authorize(Roles = "Administrador,App User,Auditor")]
        public static void GuardarEntrada(string Logged,Ticket ticket)
        {
            using (var db = new SisparkModel())
            {
                var user = db.User.FirstOrDefault(u => u.Usuario == Logged);
                var TicLog = db.TicketLog.Create();
                TicLog.UserId = user.UserId;
                TicLog.DateTimeLog = DateTime.Now;
                TicLog.TransactionType = "Entrada";
                TicLog.TicketId = ticket.TicketId;

                db.TicketLog.Add(TicLog);
                db.SaveChanges();
            }
            
        }

        [Authorize(Roles = "Administrador,App User,Auditor")]
        public static void GuardarSalida(string Logged, Ticket ticket)
        {
            using (var db = new SisparkModel())
            {
                var user = db.User.FirstOrDefault(u => u.Usuario == Logged);
                var TicLog = db.TicketLog.Create();
                TicLog.UserId = user.UserId;
                TicLog.DateTimeLog = DateTime.Now;
                TicLog.TransactionType = "Salida";
                TicLog.TicketId = ticket.TicketId;

                db.TicketLog.Add(TicLog);
                db.SaveChanges();
            }

        }

        [Authorize(Roles = "Administrador,App User,Auditor")]
        public static void GuardarCancelado(string Logged, Ticket ticket)
        {
            using (var db = new SisparkModel())
            {
                var user = db.User.FirstOrDefault(u => u.Usuario == Logged);
                var TicLog = db.TicketLog.Create();
                TicLog.UserId = user.UserId;
                TicLog.DateTimeLog = DateTime.Now;
                TicLog.TransactionType = "Cancelado";
                TicLog.TicketId = ticket.TicketId;

                db.TicketLog.Add(TicLog);
                db.SaveChanges();
            }

        }

        //
        // GET: /TicketLogs/
        [Authorize(Roles = "Administrador,Auditor")]
        public ActionResult Index(string LogTransaccion, string userseek, string patenteseek, string fechaDesde, string fechaHasta)
        {
            var ListaTransaccion = new List<string>();

            var ConsultaTransaccion = from d in db.TicketLog
                                      orderby d.TransactionType
                                      select d.TransactionType;
            ListaTransaccion.AddRange(ConsultaTransaccion.Distinct());
            ViewBag.LogTransaccion = new SelectList(ListaTransaccion);

            var ListaUser = new List<string>();

            var ConsultaUser = from u in db.TicketLog
                               orderby u.User.Usuario
                               select u.User.Usuario;
            ListaUser.AddRange(ConsultaUser.Distinct());
            ViewBag.userseek = new SelectList(ListaUser);

            var ListaPatente = new List<string>();

            var ConsultaPatente = from p in db.TicketLog
                                  orderby p.Ticket.Car.Patente
                                  select p.Ticket.Car.Patente;
            ListaPatente.AddRange(ConsultaPatente.Distinct());
            ViewBag.patenteseek = new SelectList(ListaPatente);

            var tlogs = from l in db.TicketLog
                        select l;

            if (!String.IsNullOrEmpty(fechaDesde))
            {
                DateTime fecha1 = Convert.ToDateTime(fechaDesde);
                tlogs = tlogs.Where(fd => fd.DateTimeLog >= fecha1);
            }

            if (!String.IsNullOrEmpty(fechaHasta))
            {
                DateTime fecha2 = Convert.ToDateTime(fechaHasta);
                tlogs = tlogs.Where(fd => fd.DateTimeLog >= fecha2);
            }

            if (!String.IsNullOrEmpty(patenteseek))
                tlogs = tlogs.Where(p => p.Ticket.Car.Patente == patenteseek);

            if (!String.IsNullOrEmpty(userseek))
                tlogs = tlogs.Where(u => u.User.Usuario == userseek);

            if (string.IsNullOrEmpty(LogTransaccion))
                return View(tlogs);
            else
                return View(tlogs.Where(t => t.TransactionType == LogTransaccion));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/TicketLogs/Index.cshtml
@model IEnumerable<SisPark.Models.TicketLog>

@{
    ViewBag.Title = "Log de Ticket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Log de Ticket</h2>

@using (Html.BeginForm("Index","TicketLogs", FormMethod.Get))
{
    <p>
        Transacción: @Html.DropDownList("LogTransaccion","")
        Usuario: @Html.DropDownList("userseek","")
        Patente: @Html.DropDownList("patenteseek","")
    </p>
    <p>
        Fecha Desde:<input type="date" name="fechaDesde" />
    </p>
    <p>
        Fecha Hasta:<input type="date" name="fechaHasta" />
    </p>
    <p>
        <input type="submit" value="Filtrar" />
    </p>
}
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Car.Patente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTimeLog)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Car.Patente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Usuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTimeLog)
        </td>
    </tr>
}
</table>